import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DesktopHero from "@/components/Heros/Desktop-Hero";
import Sponsors from "@/components/Sponsors/sponsors";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <DesktopHero />
      </div>
      <div>
        <Sponsors />
      </div>
    </div>
  );
}
